version: '3.7'
networks: 
  default:
    external:
      name: shared
  keycloak-net:
# Settings and configurations that are common for all containers
services:
  keycloak-db:
    image: postgres:11-alpine
    volumes: 
      - keycloak-datastore:/var/lib/postgresql/data
    networks:
      - keycloak-net
    env_file:
      - .env

  keycloak:
    image: jboss/keycloak:15.0.2
    depends_on:
      - keycloak-db
    networks:
      - keycloak-net
      - default
    ports:
      - "8180:8080"
    env_file:
      - .env
## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  keycloak-datastore:
